osx_image: xcode10
language: objective-c
xcode_project: ClassWrittenInSwift
xcode_scheme: ClassWrittenInSwiftKit
xcode_sdk: iphoneos12.0
env:
  global:
  - FRAMEWORK_NAME=ClassWrittenInSwiftKit
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
script: xcodebuild -project ClassWrittenInSwift/ClassWrittenInSwift.xcodeproj -scheme ClassWrittenInSwift
  -configuration Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
deploy:
  provider: releases
  file: ClassWrittenInSwiftKit.framework.zip
  skip_cleanup: true
  on:
    repo: yulingtianxia/TBUIAutoTest
    tags: true
